version: "3"
services:
    jenkins:
        image: jenkins-custom
        build:
            dockerfile: Dockerfile
        container_name: jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        networks:
            - jenkins
        volumes:
            - jenkins_home:/var/jenkins_home

networks:
    jenkins:
volumes:
    jenkins_home:
