version: "3.1"
services:
    db:
        image: postgres:15
        environment:
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_USER=odoo
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        volumes:
            - postgresql-data:/var/lib/postgresql/data
            - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
        command: -c 'config_file=/etc/postgresql/postgresql.conf'
        networks:
            - backend
        restart: always

    odoo16:
        image: xmars/odoo:16
        build:
            context: dockerfile
            dockerfile: Dockerfile
        container_name: odoo-16
        depends_on:
            - db
        environment:
            - HOST=db
            - PORT=5432
            - USER=odoo
            - PASSWORD=odoo
        ports:
            - "8069:8069"
            - "8072:8072"
        volumes:
            - ../:/mnt/custom-addons # customize addons
            - ./et-addons:/mnt/et-addons # odoo enterprise addons
            - ./etc:/etc/odoo
            - ./logs:/var/log/odoo
            - odoo-data:/var/lib/odoo
        networks:
            - frontend
            - backend
        restart: always
    # fixme: uncomment nginx section
    # nginx:
    #     image: nginx
    #     depends_on:
    #         - odoo16
    #     volumes:
    #         - ./nginx:/etc/nginx/conf.d
    #     ports:
    #         - "80:80"
    #     networks:
    #         - frontend

volumes:
    odoo-data:
    postgresql-data:

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge
